---
collections:
  - name: community.network
    version: 5.1.0
    source: https://galaxy.ansible.com
  - name: awx.awx
    version: 24.6.1
    source: https://galaxy.ansible.com
  - name: netapp.aws
    version: 21.7.1
    source: https://galaxy.ansible.com
  - name: sophos.sophos_firewall
    version: 2.5.1
    source: https://galaxy.ansible.com
...